{"created": 1739204656.85181, "duration": 0.262861967086792, "exitcode": 1, "root": "/Users/daniloamedeiros/Desktop/projeto desafio atualizado /qa-automation-desafio", "environment": {}, "summary": {"failed": 1, "total": 1, "collected": 1}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "ui_tests/tests/test_performace.py::test_performance", "type": "Function", "lineno": 2}]}], "tests": [{"nodeid": "ui_tests/tests/test_performace.py::test_performance", "lineno": 2, "outcome": "failed", "keywords": ["test_performance", "test_performace.py", "tests", "ui_tests", "qa-automation-desafio", ""], "setup": {"duration": 0.00018100003944709897, "outcome": "passed"}, "call": {"duration": 0.24724662501830608, "outcome": "failed", "crash": {"path": "/Users/daniloamedeiros/Desktop/projeto desafio atualizado /qa-automation-desafio/ui_tests/tests/test_performace.py", "lineno": 18, "message": "AssertionError: Locust command returned a non-zero exit code\nassert False"}, "traceback": [{"path": "test_performace.py", "lineno": 18, "message": "AssertionError"}], "stdout": "Locust command failed\n\n", "longrepr": "def test_performance():\n        # Executa o Locust\n        result = subprocess.run(\n            [\"locust\", \"-f\", \"locustfile.py\", \"--headless\", \"-u\", \"100\", \"-r\", \"10\", \"--run-time\", \"10s\",\n             \"--host=http://localhost:5001\"],\n            stdout=subprocess.PIPE,\n            stderr=subprocess.PIPE,\n            text=True\n        )\n    \n        # Armazena a sa\u00edda\n        locust_output = result.stdout\n        if result.returncode != 0:\n            print(\"Locust command failed\")\n            print(locust_output)\n>           assert False, \"Locust command returned a non-zero exit code\"\nE           AssertionError: Locust command returned a non-zero exit code\nE           assert False\n\ntest_performace.py:18: AssertionError"}, "teardown": {"duration": 0.0001015419838950038, "outcome": "passed"}}]}